// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("Hystrix")]
[assembly: AssemblyDescriptionAttribute("Hystrix.NET")]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyProductAttribute("Hystrix")]
[assembly: AssemblyCopyrightAttribute("Copyright ©  2016")]
[assembly: AssemblyVersionAttribute("1.0.0.0")]
[assembly: AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: AssemblyInformationalVersionAttribute("1.0.0-beta.4+10.Branch.release-1.0.0.Sha.6a442ef2b30ce04f1331d3de7eb4b8d4a70bfe15")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0.0.0";
    }
}
