// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("Hystrix")]
[assembly: AssemblyDescriptionAttribute("Hystrix.NET")]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyProductAttribute("Hystrix")]
[assembly: AssemblyCopyrightAttribute("Copyright ©  2016")]
[assembly: AssemblyVersionAttribute("1.0.0.0")]
[assembly: AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: AssemblyInformationalVersionAttribute("1.0.0-beta.3+4.Branch.release-1.0.0.Sha.f5114f63054eeb017e19074db6b18d4d6b53a9e2")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0.0.0";
        internal const string InformationalVersion = "1.0.0-beta.3+4.Branch.release-1.0.0.Sha.f5114f63054eeb017e19074db6b18d4d6b53a9e2";
    }
}
